- name: create data folder
  shell: mkdir -p /data/wwwroot/{{ domain }} && chown -R 9999:9999 /data/wwwroot/{{ domain }}

- name: create project logs subfolder
  shell: mkdir -p /data/logs/php

- name: call python3
  shell: rm -rf /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- name: run php-fpm service
  community.docker.docker_container:
    name: php-fpm
    image: registry.yunzmall.com/yunzhong/shop:php-fpm
    detach: yes
    restart_policy: always
    networks:
      - name: yzshop
    network_mode: yzshop
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ webpath }}:/data/wwwroot/yzshop:rw"
      - /data/logs/php:/usr/local/etc/var/log:rw

- name: recovery python2
  shell: rm -rf /usr/bin/python && ln -s /usr/bin/python2 /usr/bin/python
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7